### ISSUE TITLE
Indicator stuck on 'hola' after waking up from suspend

### ISSUE THREAD

**Issue by antoinemeyer** [xynium/PingIndic#1]
After waking up from sleep, the indicator seems stuck.
Tried deactivating/reactivating but does not work. Only restarting the computer works.

ps: Thanks a lot for this extension, it's very useful.

**Comment by xynium** [comment]
Hi,
I sometime (rarely) observe that, also after a sleep hibernate. 
At this time i have absolutely no clue of where it came from (and no much time to investigate).
I use ubuntu 22.04 gnome 42.4
What gnome version are you using ?
JP

**Comment by antoinemeyer** [comment]
> Hi, I sometime (rarely) observe that, also after a sleep hibernate. At this time i have absolutely no clue of where it came from (and no much time to investigate). I use ubuntu 22.04 gnome 42.4 What gnome version are you using ? JP

Salut JP, 
I'm on ubuntu 22.04 with gnome 42.0.
Is there a way to restart the ping when this situation happens? Even manually?

**Comment by xynium** [comment]
Hi Antoine,
the problem is that it is a random bug, so it is not easy to diagnose.
From the extension side, and with my (basic) knowledge of gnome there is no way to interact with the pause resume sequence (as it is in android).
I have added to extension.js a new message (that appear in the indicator) in case the problem is due to the launching of the ping. This may help to diagnose the cause.
JP

**Comment by antoinemeyer** [comment]
I got the following in my `journalctl /usr/bin/gnome-shell -f -o cat`:
```
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55850f3b0310] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55851760ab20] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55851760c340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55850f3b0310] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55851192bae0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55851192f860] is on because it needs an allocation.
JS ERROR: GLib.Error g-unix-error-quark: Too many open files
loadData@/home/antoine/.local/share/gnome-shell/extensions/pingindic@xynium.github.com/extension.js:92:83
update@/home/antoine/.local/share/gnome-shell/extensions/pingindic@xynium.github.com/extension.js:156:16

Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55850f3b0310] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55851760b6f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55851760c340] is on because it needs an allocation.
```

Note that my refresh rate is 1s.

Potentially related: https://github.com/konkor/cpufreq/issues/178 (fixed in https://github.com/konkor/cpufreq/commit/fe2977b8afe069468eddaa28676625a1da6dfb77)

Maybe `GLib.spawn_close_pid` must be called somewhere?

**Comment by xynium** [comment]
Hi Antoine,
Thanks you for your log
I think this error is due to your refresh rate too low.
The ping instruction is launched in non blocking mode, so you may launch  a new ping with an other still executing. And in a while you may have to much ping in execution.
My refresh rate is much to long i have 100s. And since a good while i don't have any crash.
Check with top, that you don't have zombie process
JP
